### ISSUE TITLE
Add types to parser

### ISSUE THREAD

**Issue by shuai626** [shuai626/moot#1]
* int
* bool
* char
* inductively typed boxes
* inductively typed pairs
* string of constant length; 
* mutable vectors of constant length
* first-class functions;

**Comment by npateel** [comment]
![image](https://user-images.githubusercontent.com/32022743/161588076-a03e36fa-0c57-40a7-908c-393787d29b28.png)
We're basically going to be implementing this CFG in a recursive parser


Right now, 
Blame Labels (maybe just implement as string)
Type values
Typed parameters

Expressions of the following:
(ann E T l)
lambda
let / letrec
and typed define

are all not implemented in `parse.rkt`. We need to add pattern matching to [parse](https://github.com/shuai626/moot/blob/90c4b3a1f49e6a1b8f78f351442c3a70aae9563b/loot/parse.rkt#L6) or parse-def/parse-e to implement this

Each of the unimplemented types need to have some sort of AST representation to them. 

I suggest the following:
```
Integer -> IntType
Any -> DynType
Boolean -> BoolType
Unit -> UnitType
() -> UnitType
(-> Type... Type) ->   (FunType (ParamTypes...) ReturnType) = (FunType (IntType FloatType) DynType)
(Tuple Type...) -> (TupleType (Types...)) = (TupleType (IntType FloatType DynType))
(Ref Type) -> (RefType Type) = (RefType IntType)
(Vect Type) -> (VectType Type)
(Rec x Type) -> (RecType x Type) = (RecType typeNameHere IntType)
```

Note that let / define / lambda need to now support typing. Since they take parameters, I suggest representing them as
`(Type symbol)`. An example would be `(BoolType isEqual)`

So something like

```racket
(let ((sum : Integer 5)
      (count (get-count)))
(+ sum count) )
```
could have `let` represented as `(Let ((IntType sum) (DynType count) ((Int 5) (Fun ...)) (Prim + (Var sum) (Var count))`
so `(Let ((type var)) expr expr)` (since our current compiler doesn't handle multiple let)

Functions are similar:
```racket
(define (f (sum : Integer) count) : Int
    (+ sum count))
```
could be represented as 
`(Defn f ((IntType sum) (DynType count)) IntType (Prim  + (Var sum) (Var count)))`
So
`(Defn x ((Type x)...) ReturnType expr)`


Lambdas are similar as well. They become:
`(Lam (gensym 'lambda) ((Type x)...) ReturnType expr)`

**Comment by npateel** [comment]
As for implementation details, my recommendations are the following:
0. IMMEDIATE: Find out if S-Expr with types are supported in racket. Try adding the `define` above and parsing it
If we can't. We'll have to come up with another way to represent types in Racket. Maybe by having the input be `(define f (sum Int) (count Dyn)  Int expr)`

Maybe try typed racket too if it doesn't work


2. Implement a function `prim-to-type` which will match `Int` to `IntType`, `Bool` to `BoolType`, `Unit` to `UnitType` AND `()` to `UnitType` (some syntax sugar).
3. Replace the `symbol?` assertion in `parse-define`, the `let` and `lambda` branch of `parse-e` with a `parameter?` function that will check that each parameter is a properly formed variable.
4. Add a function `parse-parameter-list` to parse a parameter list for the `let` `lambda` and `define` branches of the parser (since we can't just use the raw symbols anymore
5. Parse the return type and add to the `Defn` return

**Comment by ryansdowning** [comment]
@npateel I started implementing this last night, but didn't quite grasp the grammar presented for types. Particularly, why are we equating some types to `IntType` and `FloatType`? i.e.

```
(Type... -> Type) ->   (FunType (Param Types...) ReturnType) = (FunType (IntType FloatType) DynType)
(Tuple Type...) -> (TupleType (Types...)) = (TupleType (IntType FloatType DynType))
(Ref Type) -> (RefType Type) = (RefType IntType)
(Rec x Type) -> (RecType x Type) = (RecType typeNameHere IntType)
```

**Comment by npateel** [comment]
Sorry, these were just examples of expansions for each of the grammars. The middle ones are what should be implemented

**Comment by ryansdowning** [comment]
@npateel will `typeNameHere` in `RecType` just be a symbol?

**Comment by ryansdowning** [comment]
Any suggestions for implementing the `parameter?` parse branch?

**Comment by npateel** [comment]
You are correct in that typeNameHere is a symbol?

For parameter? I'll try to come up with a parse grammar tomorrow to help with implementation. 

It might actually be better to just parse according to the grammar optimistically, and throw errors if any of the parses fail.
